name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: ✅ Test
    steps:
      - name: 🛑 Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: ⬇️ Checkout repository
        uses: actions/checkout@v2

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: 📥 Install dependencies
        uses: bahmutov/npm-install@v1

      - name: ✅ Run tests
        run: yarn test
        env:
          CI: true

      - name: 📦 Run build
        run: yarn build
